### ISSUE TITLE
请问弹出的通知内容是否支持超链接

### ISSUE THREAD

**Issue by twypx** [shanghaobo/http-win-notice#21]

**Comment by shanghaobo** [comment]
- windows弹窗内容不支持超链接，可以通过加按钮的方式实现
- 目前这个项目没有适配自定义按钮和链接，有能力可以改造以下代码部分实现：
https://github.com/shanghaobo/http-win-notice/blob/6081b3592c438a5156a4453e5f46f99e358c2428/utils/notice/notice.go#L92-L100

**Comment by shanghaobo** [comment]
已支持 #22
