### ISSUE TITLE
Toast notification not working on specific Windows version

### ISSUE THREAD

**Issue by ShellBin** [shanghaobo/http-win-notice#4]
Target: Windows 10 Enterprise Edition LTSC 1809(17763.2300)

The notification is not shown, no sound is played and no error is returned.

Here are some documents that might help with this issue:
[Toast notification not working on Windows fall creators update](https://stackoverflow.com/questions/46814858/toast-notification-not-working-on-windows-fall-creators-update)

**Comment by shanghaobo** [comment]
- 我搜到一篇这个，不排除是这个版本windows本身的问题：https://answers.microsoft.com/zh-hans/windows/forum/all/win10/46d5973d-bfce-49b3-bacc-d429accc2471?page=1

- 本工具是基于https://github.com/go-toast/toast 库，您也可以先尝试直接下载使用他的cli运行，看是否有问题来帮助排查原因，以下步骤来自`go-toast/toast`仓库readme：
  
  As well as using go-toast within your Go projects, you can also utilise the CLI - for any of your projects.
  
  Download [64bit](https://go-toast-downloads.s3.amazonaws.com/v1/toast64.exe) or [32bit](https://go-toast-downloads.s3.amazonaws.com/v1/toast32.exe)
  
  ```cmd
  C:\Users\Example\Downloads\toast64.exe \
    --app-id "Example App" \
    --title "Hello World" \
    --message "Lorem ipsum dolor sit amet, consectetur adipiscing elit." \
    --icon "C:\Users\Example\Pictures\icon.png" \
    --audio "default" --loop \
    --duration "long" \
    --activation-arg "https://google.com" \
    --action "Open maps" --action-arg "bingmaps:?q=sushi" \
    --action "Open browser" --action-arg "http://..."
  ```

**Comment by ShellBin** [comment]
谢谢您的帮助。
因为测试环境受限，我只在这台机器上试过 node-notifier 内置的 Windows 推送组件 [snoretoast](https://github.com/KDE/snoretoast) 

- snoretoast 可以正常推送，并注册自己为 【设置】 -> 【通知和操作】 -> 【应用列表】 中的应用。

- 而即便是 [http-win-notice](https://github.com/shanghaobo/http-win-notice) 可以正常工作的机器上也未见有注册到该列表的现象。

我对 Windows 开发一窍不通，只是根据经验初步判断是某些版本的 Windows 10 不支持未注册的应用无法获得推送功能。

谢谢您的线索，我再做一些测试。

**Comment by shanghaobo** [comment]
已经找到原因了，在下个版本将会修复，感谢反馈~

**Comment by shanghaobo** [comment]
v1.1.2 版本已修复，可以再试试
