### ISSUE TITLE
有计划添加go-toast其他支持的自定义参数功能码？

### ISSUE THREAD

**Issue by clm0081** [shanghaobo/http-win-notice#9]
RT,比如说自定义icon，自定义通知时常，提醒声音，以及自定义按钮功能？

**Comment by shanghaobo** [comment]
后边会加上，准备做成通过配置参数来控制

按钮的话只能打开url，可以做成url参数动态控制

**Comment by clm0081** [comment]
好的，持续关注中，之前找这个功能的程序找了很久。
